// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0
// source: backlog_item.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const getOneBacklogItem = `-- name: GetOneBacklogItem :one
SELECT id, type, summary, story_point
FROM backlog_items
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetOneBacklogItem(ctx context.Context, id uuid.UUID) (BacklogItem, error) {
	row := q.db.QueryRowContext(ctx, getOneBacklogItem, id)
	var i BacklogItem
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Summary,
		&i.StoryPoint,
	)
	return i, err
}
